{% set name = "changeforest" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2d734f2383d08631352170df470485e9d739cac709d36d832e425158da0c4d46

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - python
    - pip
    - maturin
  run:
    - python
    - numpy

test:
  imports:
    - changeforest
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest

about:
  home: https://github.com/mlondschien/changeforest
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Classifier based non-parametric change point detection
  description: |
    Change point detection tries to identify times when the probability distribution of a
    stochastic process or time series changes. Existing methods either assume a parametric
    model for within-segment distributions or a based on ranks or distances, and thus fail
    in scenarios with reasonably large dimensionality.

    `changeforest` implements a classifier based algorithm that consistently estimates
    change points without any parametric assumptions even in high-dimensional scenarios.
    See [1] for details.

    [1] M. Londschien, S. Kovács and P. Bühlmann (2021), "Random Forests and other
    nonparametric classifiers for multivariate change point detection", working paper.
  dev_url: https://github.com/mlondschien/changeforest

extra:
  recipe-maintainers:
    - mlondschien
